site_name: UAB Research Computing DevOps Docs
repo_url: https://github.com/uabrc/devops-docs

theme:
  name: material
  search_index_only: true
  custom_dir: theme
  language: en
  features:
    - navigation.indexes
    - navigation.instant

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2021-2022 The University of Alabama at Birmingham.<br /><b>Still stuck after reading?</b> Email us at <a href="mailto:support@listserv.uab.edu" class="supportemail">support@listserv.uab.edu</a>

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.keys
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - table-reader:
      data_path: docs
  - git-revision-date-localized:
      type: date
  - glightbox:
      # auto_caption: true
  - redirects:
      redirect_maps:

nav:
  - Home: index.md
  - Cheaha:
    - Archiving Modules: cheaha/archiving_modules.md
    - Shell Commands: cheaha/shell_commands.md
  - Gitlab Runner:
    - Personal Gitlab Runner Setup: gitlab_runner/personal_gitlab_runner_setup.md
  - Openstack:
    - VM Migration: openstack/vm_migration.md
    - VM Service Setup: service/service_setup.md
