site_name: UAB Research Computing DevOps Docs
repo_url: https://github.com/uabrc/devops-docs
edit_uri: blob/main/docs/

theme:
  name: material
  search_index_only: true
  custom_dir: theme
  language: en
  features:
    - navigation.indexes
    - navigation.instant
    - content.code.copy
    - content.action.edit
    - content.tabs.link
  favicon: images/favicon.png
  logo: images/logo.png

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; The University of Alabama at Birmingham.

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - toc:
      permalink: true

plugins:
  # order matters!
  - search
  - meta
  - blog:
      archive_date_format: MMMM yyyy
      archive_url_date_format: yyyy/MM
      blog_dir: news
      blog_toc: true
      post_date_format: full
      post_excerpt: required
      post_readtime: false
      categories_allowed:
        - Known Issues
        - Maintenance
        - Outreach
        - Releases
        - Survey
  - gen-files:
      scripts:
        - scripts/pandoc_generator.py
  - git-revision-date-localized:
      type: date
      strict: false
  - glightbox
  - table-reader:
      data_path: docs
  - title-casing

exclude_docs: |
  /**/res/*.md
  /**/_macro/
  /**/_template/

not_in_nav: |
  /**/res/*.md
  /**/_macro/
  /**/_template/

nav:
  - Home: index.md
  - Cheaha:
      - Archiving Modules: cheaha/archiving_modules.md
      - Shell Commands: cheaha/shell_commands.md
  - GitLab Runner:
      - Personal GitLab Runner Setup: gitlab_runner/personal_gitlab_runner_setup.md
  - Openstack:
      - VM Migration: openstack/vm_migration.md
      - VM Service Setup: service/service_setup.md
      - Share Openstack Image: openstack/share_image.md
  - Identity:
      - Saml: saml/saml.md
      - SP Metadata Generation: saml/create-sp-metadata.md
  - Ticket Issues: tickets.md

validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn
    unrecognized_links: warn

watch:
  - macros
  - res
  - scripts
  - theme
