name: ci

on:
  push:
    branches:
      - dev
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: build_env.yml
          environment-name: build
          cache-downloads: true
          cache-env: true

      - name: Build pages
        shell: bash -l {0}
        run: |
          micromamba activate build
          mkdocs gh-deploy --force --strict
